"""Regenerate the five static course pages and instructional SVGs. No dependencies."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).parent
DIST = ROOT / 'dist'

def table(headers, rows):
    return '<div class="table-wrap"><table><thead><tr>' + ''.join(f'<th scope="col">{v}</th>' for v in headers) + '</tr></thead><tbody>' + ''.join('<tr>'+''.join(f'<td>{v}</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'

def picture(name, title, boxes, caption):
    # Schematics show the exact lab flow; these are illustrations, not screenshots.
    width = 900
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} 260" role="img"><title>{escape(title)}</title><rect width="900" height="260" fill="#eef1e5"/><text x="30" y="38" fill="#173e39" font-family="sans-serif" font-size="21" font-weight="bold">{escape(title)}</text>']
    for i, (heading, lines) in enumerate(boxes):
        x = 30+i*290
        parts.append(f'<rect x="{x}" y="65" width="260" height="155" rx="8" fill="white" stroke="#94a88e"/><circle cx="{x+25}" cy="92" r="13" fill="#173e39"/><text x="{x+25}" y="97" text-anchor="middle" fill="#d9ef88" font-family="sans-serif" font-size="14">{i+1}</text><text x="{x+48}" y="98" fill="#173e39" font-family="sans-serif" font-size="17" font-weight="bold">{escape(heading)}</text>')
        for j,line in enumerate(lines):
            parts.append(f'<text x="{x+17}" y="{133+j*26}" fill="#425d52" font-family="sans-serif" font-size="16">{escape(line)}</text>')
        if i<2: parts.append(f'<path d="M{x+266} 145h17m-6-6 6 6-6 6" fill="none" stroke="#173e39" stroke-width="2"/>')
    parts.append('</svg>')
    (DIST/'assets'/f'{name}.svg').write_text(''.join(parts),encoding='utf-8')
    return f'<figure><img src="assets/{name}.svg" alt="{escape(title)}: {escape("; ".join(h+" — "+", ".join(l) for h,l in boxes))}" width="900" height="260"><figcaption>{caption} · Lab illustration</figcaption></figure>'

def solution(text): return f'<details><summary>Show the solution and troubleshooting</summary>{text}</details>'

modules = []
modules.append(dict(title='Motivation', subtitle='Think like an attacker. Decide what to defend.', time='60–75 minutes', level='Start here · no prerequisites',
 intro='Why would someone attack a community learning centre? Follow the incentives, identify what matters, and learn to recognise an incident before it becomes a crisis.',
 objectives=['Explain financial, political, personal, and curiosity-driven attacker motivations.', 'Distinguish confidentiality, integrity, availability, authentication, and accountability.', 'Trace an attacker’s lifecycle and connect common attacks to defensive controls.', 'Use major breach lessons to identify practical improvements.'],
 lecture='''<h3>1. Security starts with people and purpose</h3>
<p>Information security protects information and the systems that handle it. Cybersecurity focuses on digital systems; information security also includes a printed attendance list left on a desk. Neither means removing every risk. We protect what matters, in proportion to the harm a failure could cause.</p>
<p>Imagine a community learning centre that offers evening classes. It holds learner contact details, attendance records, and payment information. These are <strong>assets</strong>: things with value. A criminal wanting to steal them is a <strong>threat actor</strong>. A reused staff password is a <strong>vulnerability</strong>: a weakness. Requiring a second login factor is a <strong>control</strong>: a measure that reduces risk. <strong>Risk</strong> combines how likely a harmful event is with its consequences.</p>
<p>Attackers have different incentives. Criminals may seek money through fraud, stolen data, or ransomware. State-linked actors may seek intelligence or disruption. Ideological groups may seek publicity. An unhappy insider may seek revenge, while a curious person may want to prove skill. An insider can also cause harm accidentally. These motives can overlap; a log entry alone rarely proves who acted or why.</p>
<p>Defenders want the centre to keep teaching, protect learners, meet obligations, and maintain trust. They have limited time and money. The question is: which control most reduces the harm that matters to this organisation?</p>
<h3>2. What are we protecting?</h3>'''+table(['Goal','Plain meaning','At the centre'],[
('Confidentiality','Only authorised people can see information.','Keep learner contact details private.'),('Integrity','Information stays accurate; unauthorised changes are prevented or detected.','Stop someone changing a refund amount.'),('Availability','People can use a service when needed.','Keep class registration usable during enrolment.'),('Authentication','Establish who or what is making a request.','Check a staff member’s identity at login.'),('Accountability','Make actions traceable to responsible identities.','Record who exported learner records.')])+'''
<p>The first three goals form the <strong>CIA triad</strong>. A ransomware incident can affect all three: files become unavailable, records may change, and copies may be stolen. Authentication differs from authorisation: proving that you are a volunteer does not give you permission to view payroll.</p>
<h3>3. An attack is a chain of opportunities</h3>
<p>A useful simplified lifecycle is <strong>reconnaissance → initial access → execution → persistence and privilege escalation → lateral movement → impact</strong>. Reconnaissance gathers information. Initial access opens a door. Execution runs attacker-controlled activity. Persistence helps the attacker return; privilege escalation gains stronger permissions. Lateral movement reaches other systems. Impact may mean stealing information, changing records, or disrupting service. Real attacks may skip stages, repeat them, or take a different order.</p>
<p>A phishing email can trick a staff member into revealing a password. Credential stuffing tries passwords exposed elsewhere. Exploiting unpatched software uses a known weakness. Malware is software intended to cause harm. Social engineering manipulates people rather than breaking cryptographic mathematics. A denial-of-service attack overwhelms a service. None requires the attacker to be a cinematic genius: ordinary weaknesses often combine.</p>
<p>Map controls to the chain: updates close known vulnerabilities; phishing-resistant multi-factor authentication makes stolen passwords less useful; limited permissions reduce escalation; segmentation restricts movement; monitoring detects unusual activity; tested backups help recovery. No single control solves the whole chain.</p>
<h3>4. Learn from large breaches</h3>
<p>In the 2017 Equifax breach, the US Federal Trade Commission alleged that a known Apache Struts vulnerability went unpatched and that organisational failures contributed to the exposure. The lesson is to give each system an owner and verify fixes, rather than treating a patch announcement as proof of completion. <a href="https://www.ftc.gov/business-guidance/blog/2019/07/575-million-equifax-settlement-illustrates-security-basics-your-business">Read the FTC’s case analysis</a>.</p>
<p>Ransomware incidents illustrate a different operational lesson: recovery needs preparation. Keep backups separated from everyday account access, test restoration, and plan who will coordinate response. <a href="https://www.cisa.gov/stopransomware/ransomware-guide">CISA’s ransomware guide</a> connects prevention with response and recovery. A backup can restore files, but it cannot undo disclosure of a stolen copy.</p>
<div class="callout"><strong>Pause and apply</strong><p>A staff member can sign in but cannot open the learner directory. Which goal failed? It may be availability for that staff member, or an intended authorisation restriction. Security analysis starts by establishing what should happen.</p></div>''',
 videos=[('kPPFNrlN3zo','What is the CIA Triad','IBM Technology','Use this visual explanation for the security-goals portion. Then follow the incident walkthrough below to cover attacker motives and the lifecycle.')],
 labtitle='Investigate a simulated incident',
 labintro='You are the centre’s incident reviewer. Analyse fictional events, choose the main security goal at risk, and find a control that would interrupt the chain. Nothing connects to an outside system.',
 steps=['Read the event log below. Write down the earliest suspicious event and explain why it is suspicious.', 'Trace the events: reconnaissance is not shown; find initial access, escalation, and impact. Do not assume that a successful login identifies the attacker.', 'Select the primary security goal affected by the export and click Check analysis.', 'Write one control for initial access and one for impact. Open the solution to compare your reasoning.'],
 figures=[('incident','From stolen access to data theft',[('Initial access',['Reused staff password','Successful login']),('Escalation',['Volunteer gains admin','Excess permission']),('Impact',['Learner file exported','Confidentiality at risk'])],'Follow the evidence from account access to data export.')],
 workspace='''<div class="log">09:00 · 12 failed logins for volunteer@centre.example<br>09:04 · Successful login from a new device<br>09:07 · Volunteer account granted administrator access<br>09:09 · Learner directory exported: 240 fictional records</div><label for="goal">Primary goal affected by the export</label><select id="goal"><option value="">Choose a goal</option><option>Confidentiality</option><option>Integrity</option><option>Availability</option></select><button id="incident-check">Check analysis</button><output id="incident-result" aria-live="polite">Your finding will appear here.</output>''',
 solution='''<p>The failed logins followed by a new-device login warrant investigation, but are not proof of intrusion. The login is possible initial access; the admin grant is possible escalation; the export is impact. Exporting records to an unauthorised person primarily harms <strong>confidentiality</strong>. The permission change also threatens integrity.</p><p>A financial motive is plausible if the records can support fraud; the log does not prove it. Unique passwords and phishing-resistant MFA reduce stolen-account risk. Restrict admin grants, review privileges, and alert on bulk exports. Preserve logs and involve the incident lead before making disruptive changes.</p><p>If the checker asks you to choose a goal, select one in the menu first. You may retry freely. Refreshing resets this exercise.</p>''',
 check=('A ransomware attacker both copies and encrypts records. Which CIA goals could be affected?','All three: disclosure affects confidentiality, unauthorised modification can affect integrity, and blocked access affects availability.'),
 summary=['Attacker incentives help you anticipate likely harm; evidence is needed to establish attribution.', 'Use the CIA triad to state what must be protected, and distinguish identity from permission.', 'Break the attack chain at several points and prepare for recovery.', 'Assign owners, verify controls, and learn from incidents.'],
 sources=[('CISA · Ransomware prevention and response','https://www.cisa.gov/stopransomware/ransomware-guide')]))

modules.append(dict(title='Security Design',subtitle='Build fewer opportunities for harm.',time='70–90 minutes',level='Build on Module 1',
 intro='A secure system helps people do the right thing. Design a centre portal that limits damage, checks permission, and remains simple enough to use.',
 objectives=['Apply least privilege and check authorisation for every protected action.', 'Identify weak links, trust boundaries, and layered controls.', 'Explain how simplicity, usability, and secure defaults affect design.', 'Test and repair an access-control flaw in a simulated portal.'],
 lecture='''<h3>1. Design around what could go wrong</h3>
<p>Security design begins before choosing products. For the centre portal, draw where information goes: a learner’s browser sends a request to the portal, which reads the learner database. An email service sends reminders. Each point where control or trust changes is a <strong>trust boundary</strong>. Treat a browser request as untrusted even if the interface looks legitimate.</p>
<p>A simple <strong>threat model</strong> asks four questions: what are we building, what could go wrong, what will we do about it, and how will we check? A learner might request somebody else’s record. A compromised reminder service might receive too much information. A failed database might stop registrations. The goals from Module 1 tell us why these failures matter.</p>
<h3>2. Give each role only what it needs</h3>
<p><strong>Least privilege</strong> means giving people and software the smallest set of permissions needed for their work, for as long as needed. Learners need their own records; volunteers need class attendance; finance staff need payment records. A reminder service needs an email address and class time, not payment history. A separate admin account can make unusual elevated activity easier to review.</p>
<p><strong>Complete mediation</strong> means checking permission each time a protected resource is accessed. Hiding an admin button is insufficient: an attacker can send the request another way. The server must check the authenticated user’s role and their relationship to the requested record. A guessed record number must never become permission.</p>
<p>In this module’s simulator, the first rule deliberately checks only whether a person is logged in. Changing the requested record reveals another learner’s details. The repair checks ownership too. In a real system this enforcement belongs on the server; browser-only checks are editable by the user.</p>
<h3>3. Find the weakest link and add layers</h3>
<p>A strong front door helps little if an unlocked window bypasses it. Likewise, excellent encryption cannot compensate for an account that is allowed to download every record. Review password recovery, support access, backup storage, and third-party integrations as well as the main login.</p>
<p><strong>Defence in depth</strong> uses controls with different purposes: MFA at login, authorisation at the record, segmentation around the database, export alerts, and isolated backups. Layers reduce the chance that one failure becomes a disaster. Five controls depending on the same compromised administrator may share a common failure point.</p>
<p><strong>Secure defaults</strong> start with minimal access. <strong>Fail securely</strong> means an access-check failure denies the protected request rather than letting everyone in. Plan a controlled recovery process so a fail-secure system does not leave legitimate users stranded. <strong>Separation of duties</strong> can require one person to request a large refund and another to approve it.</p>
<h3>4. Simplicity and usability are security properties</h3>
<p>Every feature, integration, and configuration adds ways to make mistakes. Reducing the <strong>attack surface</strong> means removing unnecessary exposed functions and services. Use maintained components, parameterised database queries, sensible input limits, and carefully scoped permissions. Do not invent an encryption algorithm to make the system appear special.</p>
<p>A difficult control may be bypassed. If volunteers cannot recover accounts safely, they may share one login. A usable design gives each person an account, offers clear recovery instructions, and uses understandable error messages. Security should fit the work: reminders can contain minimal information and link to a protected page.</p>
<p>There are trade-offs. Short sessions limit the window for a stolen device but interrupt teaching. A reasonable design can use longer low-risk sessions and require fresh authentication for exporting records. Describe the threat and the cost before selecting a control, then test with representative users.</p>
<div class="callout"><strong>Industry perspective</strong><p>Parisa Tabriz’s historical talk below illustrates browser security design. Focus on the design ideas, rather than treating a 2013 browser interface as current guidance. In <a href="https://blog.google/products-and-platforms/products/chrome/optimistic-dissatisfaction-status-quo-security/">her later Google essay</a>, she emphasises addressing underlying causes and sustained improvement.</p><p>A <a href="https://www.linkedin.com/blog/engineering/archive/finding-same-origin-method-execution-vulnerabilities">LinkedIn engineering case study by Nathan Walsh, with acknowledged contributions from Mukul Khullar and colleagues</a>, shows that restricting characters in an input may still leave an unintended capability. Ask what an allowed action can actually do, not just whether input looks safe.</p></div>''',
 videos=[('mD8xtn0oYeY','Chrome Security Secret Sauce','Parisa Tabriz · Strange Loop, 2013','An optional practitioner lecture on security, simplicity, and browser protection. The guided portal exercise below teaches this module’s access-control principles directly.')],
 labtitle='Find and repair a permission flaw',labintro='This is an intentionally simplified, fictional portal. You have permission to test only this simulator. It uses no real accounts or records.',
 steps=['Leave the signed-in learner as Alex (record 101) and the rule as Login only. Request record 101; Alex’s fictional record appears.', 'Change Requested record to 102 and click Request record. You can see Sam’s fictional record. Explain why being logged in is insufficient.', 'Change the rule to Login + ownership. Request 102 again: access should be denied.', 'Request 101 under the repaired rule. Alex should retain legitimate access. A secure fix must prevent abuse while preserving intended behaviour.'],
 figures=[('access','A request must cross an authorisation check',[('Browser request',['Signed in as Alex','Requested record: 102']),('Check ownership',['Alex owns record 101','102 belongs to Sam']),('Protected result',['Deny record 102','Allow Alex’s record 101'])],'The repaired rule compares the authenticated identity with the requested record.')],
 workspace='''<p><strong>Signed-in learner:</strong> Alex · record 101</p><label for="record">Requested record</label><select id="record"><option value="101">101 · Alex</option><option value="102">102 · Sam</option></select><label for="policy">Permission rule</label><select id="policy"><option value="login">Login only · vulnerable</option><option value="owner">Login + ownership · repaired</option></select><button id="request-record">Request record</button><output id="access-result" aria-live="polite">Choose a record and test the permission rule.</output>''',
 solution='''<p>The vulnerable rule allows record 102 because it only checks login. The repaired rule allows 101 and denies 102. This is a simplified example of broken object-level authorisation: knowing an identifier must not grant access to its object.</p><p>If you still see Sam after selecting the repaired rule, click Request record again; changing a menu does not issue a new request. Test all four combinations. Real-world fixes require server-side checks on every access, plus tests for other roles and actions. Our browser simulator demonstrates the decision, not a deployable security boundary.</p><p>Extra layers could include logs for denied requests and limits on bulk exports. They support the ownership check; they do not replace it.</p>''',
 check=('Would hiding the record selector repair the vulnerability?','No. A client can alter or recreate a request. The system serving the record must enforce ownership on each request.'),
 summary=['Model assets, information flows, and trust boundaries before selecting controls.', 'Apply least privilege and enforce authorisation on every protected request.', 'Review bypass routes and common dependencies across defensive layers.', 'Make secure defaults and recovery simple enough for people to use.'],
 sources=[('IBM · Principle of least privilege','https://www.ibm.com/think/topics/principle-of-least-privilege'),('Strange Loop · Talk details and attribution','https://www.thestrangeloop.com/2013/chrome-security-secret-sauce.html')]))

modules.append(dict(title='Introduction to Cryptography',subtitle='Keep a secret. Detect a change.',time='75–90 minutes',level='Build on Modules 1–2',
 intro='Discover how a key turns a readable message into ciphertext, why encryption needs authentication, and what happens when a protected message is altered.',
 objectives=['Distinguish encryption, encoding, hashing, and message authentication.', 'Explain symmetric keys, block ciphers, and cipher modes at an intuitive level.', 'Describe authenticated encryption and safe nonce use.', 'Encrypt, decrypt, and tamper with a message using AES-GCM in the browser.'],
 lecture='''<h3>1. Four transformations with different jobs</h3>
<p><strong>Plaintext</strong> is the original information; <strong>ciphertext</strong> is its encrypted form. Encryption uses an algorithm and a key to make information unreadable to someone without the right key. Decryption reverses the process. The key is the secret, while the algorithm can be public and carefully studied.</p>
<p>Encoding changes representation so data can be carried or displayed. Base64 is an encoding: anybody can reverse it without a secret. Hashing produces a fixed-length digest, like a fingerprint of data. A cryptographic hash is designed to make it difficult to reverse the digest or find different inputs with the same digest. It is not encryption and is not decrypted.</p>
<p>A hash alone does not authenticate a message. An attacker able to change a file may also replace its hash. A <strong>message authentication code</strong>, such as HMAC, uses a shared secret to help a recipient detect changes and establish that someone with the secret produced it. All holders of that shared key can create valid codes; this differs from a public-verification digital signature.</p>
<h3>2. Symmetric encryption and block ciphers</h3>
<p>In <strong>symmetric encryption</strong>, both sides share a secret key. Think of two people with copies of the same lock key. It is efficient for large amounts of data, but getting the key to the other person safely is a separate problem.</p>
<p>A <strong>block cipher</strong> transforms a fixed-size block using the key. AES operates on 128-bit blocks, which are 16 bytes. Its supported key sizes are 128, 192, and 256 bits; the block size stays the same. You do not need to perform its internal mathematics to use a trusted implementation.</p>
<p>Real messages are longer than a block. A <strong>mode of operation</strong> describes how to use the cipher across a message. ECB independently encrypts each block, allowing repeated plaintext blocks to reveal patterns; it is unsuitable for general message protection. CBC and CTR have different rules and, by themselves, do not supply message authentication. Choose an established authenticated construction rather than combining pieces casually.</p>
<h3>3. Encryption also needs tamper detection</h3>
<p><strong>Authenticated encryption</strong> protects confidentiality and detects unauthorised modification. AES-GCM is one widely used example. Its output includes ciphertext and an authentication tag. On decryption, the tag is checked. If the key, nonce, ciphertext, tag, or authenticated associated data is wrong, verification fails and the plaintext must not be used.</p>
<p><strong>Associated data</strong> is information authenticated without being encrypted, such as a message type. The receiver must supply the same associated data. This lets a protocol bind protected data to its context. Our small lab omits associated data to keep the first experiment focused.</p>
<p>A <strong>nonce</strong> is a value that must not repeat with the same key. For GCM, 12-byte nonces are customary. A nonce is not secret; it can travel with the ciphertext. Reusing one with a GCM key can seriously damage confidentiality and authentication. This lab generates a fresh random nonce for each message. A production system must manage nonce uniqueness and usage limits across restarts and many encryptions.</p>
<h3>4. The surrounding system still matters</h3>
<p>Good cryptography cannot protect a message before encryption or after decryption on a compromised device. Key storage, access control, backups, and deletion matter. If a key is lost, authorised recovery may become impossible; if it is stolen, attackers may read protected data. Use established tools and protocols with managed key lifecycles.</p>
<p>Passwords are usually less unpredictable than randomly generated keys. A password-derived key needs a suitable key-derivation function and parameters; a password database needs a purpose-built password hashing method with salts. A single fast SHA-256 hash is not an adequate password-storage design.</p>
<div class="callout"><strong>Before the lab</strong><p>The displayed Base64 is just a readable representation of encrypted bytes. It is AES-GCM and its secret key that provide protection. This teaching lab keeps a temporary key in page memory and discards it on refresh. Use fictional text only.</p></div>''',
 videos=[('O4xNJsjtN6E','AES Explained (Advanced Encryption Standard)','Computerphile','An optional deeper visual explanation of AES. Focus on fixed-size blocks and the role of the key; you can skip the matrix mathematics. Read the authenticated-encryption explanation and run the tampering experiment below.')],
 labtitle='Encrypt a message and detect tampering',labintro='Use your browser’s built-in Web Crypto implementation. A modern browser and HTTPS (or localhost for local use) are required. Your fictional message and temporary key stay in this page.',
 steps=['Enter a short fictional message, such as Class starts at 7. Click Encrypt. Compare the ciphertext with your original text.', 'Click Decrypt. You should recover the exact original message. The lab uses a temporary AES-256 key, a fresh 12-byte nonce, and a 128-bit authentication tag.', 'Click Tamper, then Decrypt again. One ciphertext byte changes; the authentication check should fail.', 'Click Encrypt to create a new valid message. Repeat with the same plaintext: the ciphertext should change because a new nonce is used. Refresh clears the key and lab state.'],
 figures=[('gcm','The authenticated-encryption experiment',[('Encrypt',['Message + secret key','Fresh nonce → ciphertext']),('Decrypt',['Same key + nonce','Valid tag → original text']),('Tamper',['Change one byte','Invalid tag → reject'])],'A tampered message is rejected rather than accepted as trustworthy plaintext.')],
 workspace='''<label for="plaintext">Fictional message</label><textarea id="plaintext" maxlength="2000">Class starts at 7.</textarea><button id="encrypt">Encrypt</button><button id="decrypt" class="secondary">Decrypt</button><button id="tamper" class="secondary">Tamper</button><output id="crypto-result" aria-live="polite">Encrypt a message to begin.</output>''',
 solution='''<p>Decrypting unchanged ciphertext recovers <code>Class starts at 7.</code>. After Tamper, decryption reports an authentication failure. The checker cannot tell whether the cause is accidental damage, deliberate alteration, or incorrect inputs; it must reject the result.</p><p>Repeated encryption of the same message produces different output because the nonce changes. The lab displays the nonce separately; the encoded ciphertext includes the tag. The key is not displayed or saved.</p><p>If you see “Web Crypto unavailable”, use a current browser on the hosted HTTPS site or serve the local files using localhost. If asked to encrypt first, click Encrypt before Decrypt or Tamper. Refreshing intentionally discards the key. This exercise is not a tool for storing important secrets.</p>''',
 check=('Does sending the nonce with the ciphertext expose the secret key?','No. The nonce is public. Its required property is uniqueness under the same key. Protect the secret key and follow the chosen mode’s rules.'),
 summary=['Encoding represents data; encryption conceals it; a hash alone does not authenticate it.', 'AES has a fixed block size and needs a suitable mode for messages.', 'Authenticated encryption detects tampering as well as protecting confidentiality.', 'Use trusted implementations and manage keys and nonces carefully.'],
 sources=[('MDN · Web Crypto encryption methods and AES-GCM','https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt'),('NIST · GCM specification, SP 800-38D','https://csrc.nist.gov/pubs/sp/800/38/d/final')]))

modules.append(dict(title='Cryptography in the Field',subtitle='Establish trust across the internet.',time='75–90 minutes',level='Build on Module 3',
 intro='Follow a secure connection from identity checks to encrypted communication. Then create and verify a digital signature on a fictional announcement.',
 objectives=['Explain public and private keys, hybrid encryption, and key agreement.', 'Distinguish digital signatures from encryption and shared-key authentication.', 'Describe certificates and a simplified TLS 1.3 handshake.', 'Verify a signature, detect a modified message, and inspect a website certificate.'],
 lecture='''<h3>1. Two keys solve a distribution problem</h3>
<p>Symmetric encryption is fast, but two strangers do not begin with a shared secret. <strong>Public-key cryptography</strong> uses related public and private keys. The private key stays protected; the public key can be distributed. The supported operation depends on the algorithm: some key pairs are for encryption, others for signatures or agreement. Do not assume a signing key can encrypt.</p>
<p>For public-key encryption, Alice encrypts to Bob’s public key and Bob decrypts with his private key. Alice still needs confidence that the public key belongs to Bob. Otherwise, an attacker could substitute their own public key. Public-key encryption is generally used as part of <strong>hybrid encryption</strong>: public-key techniques protect or establish a secret, and symmetric encryption protects the bulk data.</p>
<p><strong>Key agreement</strong>, such as ephemeral Diffie–Hellman, lets two parties derive shared key material without transmitting the final secret itself. Agreement without authentication can be intercepted by an attacker acting as a separate partner to each side. Identity checks and the full protocol are essential.</p>
<h3>2. A digital signature is not secrecy</h3>
<p>A digital signature is produced using a private signing key over a message and verified using the corresponding public key. A valid signature binds that message to that key and detects modification. It does not hide the message, guarantee its truth, or automatically establish who owns the key. The verifier must trust the public key’s association with the intended signer.</p>
<p>Imagine the centre publishes a signed notice: “Class starts at 7.” Anyone with the trusted public key can check it. If someone changes 7 to 9, verification fails. If the centre itself signs incorrect information, verification can still succeed. Signature validity and factual accuracy are different questions.</p>
<p>A signature is not simply “encryption with the private key.” Algorithms such as ECDSA use distinct signing and verification operations. Signatures can support evidence and accountability, but legal non-repudiation also depends on identity verification, key custody, and procedures.</p>
<h3>3. Certificates connect a public key to an identity</h3>
<p>A <strong>certificate</strong> associates a public key with identifiers, such as a website domain, and is signed by an issuer. Browsers validate a chain leading to a trusted root, check the hostname and validity period, and apply other certificate-policy checks. A valid certificate for a lookalike domain does not make that domain the website you intended to visit.</p>
<p>HTTPS means HTTP carried over TLS. It protects the connection to the named endpoint. A scam site can use HTTPS; the connection can be securely encrypted to the wrong person. Check the address and context as well as the connection’s security status. Never bypass a certificate warning just to complete this course.</p>
<h3>4. A simplified TLS 1.3 connection</h3>
<p>First, the browser and server exchange supported settings and ephemeral key shares. They derive handshake secrets. The server sends its certificate and proves possession of the relevant private key by signing handshake data; the browser validates the certificate and proof. Both sides exchange Finished messages to confirm the handshake and derived secrets. Application data then travels using symmetric authenticated encryption.</p>
<p>This describes a typical certificate-authenticated TLS 1.3 flow, leaving out resumption and other variants. TLS 1.3 does not use the old RSA key-transport handshake. Ephemeral agreement enables <strong>forward secrecy</strong>: later theft of the server’s long-term signing key alone should not reveal previously captured sessions, assuming ephemeral secrets were discarded. Active compromise of an endpoint remains a serious problem.</p>
<p>Modern tools package these ideas: HTTPS for browsing, secure messaging for communication, signed software updates for distribution, and encrypted backups for stored data. Ask where encryption begins and ends, who controls keys, and how identities are checked. TLS typically ends at a server or proxy; it does not automatically encrypt the database or hide information from the service operator.</p>''',
 videos=[('0TLDTodL7Lc','Transport Layer Security (TLS)','Computerphile','A visual explanation of TLS. Protocol versions differ; use the TLS 1.3 flow above as the reference for this course. Complete the signature experiment to cover message verification.')],
 labtitle='Sign, verify, and question trust',labintro='Generate a temporary ECDSA P-256 key pair and sign a fictional notice in this browser. Then inspect a real certificate without changing any browser security settings.',
 steps=['Leave the announcement as Class starts at 7. Click Sign announcement. The page creates a temporary ECDSA P-256 signing key pair and signs with SHA-256.', 'Click Verify announcement. It should pass using the corresponding public key.', 'Change 7 to 9 in the message without signing again. Click Verify announcement: it should fail. Restore the exact original text and verification should pass.', 'In a separate tab, open https://www.nist.gov. Use the browser’s site-information control beside the address, then the connection or certificate details. Labels vary by browser. Check the subject/domain, issuer, and validity dates. Record what those fields establish, and what they do not.'],
 figures=[('signature','A signature binds a key to a message',[('Sign notice',['Original message','Private key → signature']),('Verify notice',['Trusted public key','Original message → valid']),('Change notice',['7 changed to 9','Same signature → invalid'])],'Verification detects changes to the signed message.'),('certificate','Read the certificate, then check the address',[('Open site info',['Visit www.nist.gov','Use address-bar control']),('View certificate',['Check domain + issuer','Check validity dates']),('Interpret trust',['Connection identity','Not proof of honest content'])],'Browser controls differ; look for connection security or certificate details.')],
 workspace='''<label for="announcement">Fictional announcement</label><textarea id="announcement" maxlength="2000">Class starts at 7.</textarea><button id="sign">Sign announcement</button><button id="verify" class="secondary">Verify announcement</button><output id="signature-result" aria-live="polite">Sign a message to begin.</output>''',
 solution='''<p>The unchanged message verifies. Altering any signed character, including punctuation or spaces, should fail; restoring the exact text should pass. Clicking Sign after editing intentionally creates a valid signature for the edited message, so use Verify to test tampering.</p><p>The lab trusts the public key it just generated. It does not independently establish a real person’s identity. The signature is encoded in Base64 for display, not encrypted.</p><p>A certificate’s domain identifiers must cover the hostname you visit. The issuer identifies the certificate signer, and the validity interval is one part of browser validation. Do not expect a particular issuer: certificates can change. If certificate details are unavailable on a mobile browser, use a desktop browser or explain the same checks using the illustration.</p><p>If signing is unavailable, use a current browser on HTTPS or localhost. Refreshing discards the key pair and signature.</p>''',
 check=('A valid signature verifies a notice that says the class is free. Does that prove the price is correct?','No. It proves the message matches a signature produced with the corresponding private key, subject to the algorithm’s assumptions. Correctness and the signer’s identity require additional trust.'),
 summary=['Public-key methods help establish secrets and verify messages, with algorithm-specific roles.', 'Signatures detect modification and bind messages to keys; they do not conceal information.', 'Certificates help browsers connect keys to domain identities.', 'TLS combines authentication, key agreement, and symmetric authenticated encryption.'],
 sources=[('RFC Editor · TLS 1.3, RFC 8446','https://www.rfc-editor.org/rfc/rfc8446'),('MDN · Signing with Web Crypto','https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign')]))

modules.append(dict(title='Foundations in Practice',subtitle='Turn good intentions into a security programme.',time='75–90 minutes',level='Bring all four modules together',
 intro='Use a small organisation’s risks to set priorities, assign responsibility, collect evidence, and improve. Finish with a practical 90-day plan.',
 objectives=['Compare common frameworks, management standards, and assurance reports.', 'Identify scope, assets, risks, owners, and evidence for a security programme.', 'Prioritise controls and plan incident response and recovery.', 'Create and review a realistic 90-day improvement plan.'],
 lecture='''<h3>1. Compliance and security answer related questions</h3>
<p>Security asks whether risks are managed well enough for the organisation’s purpose. Compliance asks whether applicable requirements are met. Requirements may come from law, contracts, standards, or internal policy. Passing an assessment does not guarantee that incidents cannot happen; a control can exist on paper while failing in everyday use.</p>
<p>Start with scope: which services, people, locations, systems, and information does the programme cover? For our centre, include registration, the learner directory, payments, reminders, and backup arrangements. Record third-party responsibilities too. Outsourcing payments may reduce what the centre handles, but it does not automatically remove every obligation.</p>
<h3>2. Know which kind of reference you are using</h3>'''+table(['Reference','What it is','How to use it'],[
('NIST CSF 2.0','An outcome-oriented cybersecurity risk framework.','Organise work around Govern, Identify, Protect, Detect, Respond, and Recover.'),('ISO/IEC 27001:2022','Requirements for an information security management system (ISMS).','Establish a scoped, risk-based management system with ongoing review; certification assesses a defined scope.'),('PCI DSS v4.0.1','A payment-card data security standard.','Determine applicability and validation with the relevant payment stakeholders; examine card-data flows.'),('SOC 2','An independent attestation report against relevant trust services criteria.','Review scope, period, exceptions, and the customer’s responsibilities when assessing a supplier.')])+'''
<p>These are not interchangeable badges. A framework helps organise outcomes; a standard sets requirements; an assurance report describes an assessment. Legal duties vary by jurisdiction and activity, so record the requirements relevant to your actual organisation and confirm them with the responsible specialists. This lesson teaches the process, not a jurisdiction-specific legal conclusion.</p>
<p><a href="https://www.nist.gov/news-events/news/2024/02/nist-releases-version-20-landmark-cybersecurity-framework">NIST introduced Govern in CSF 2.0</a> alongside the other five functions. Governance makes decisions, accountability, and oversight explicit. The functions work together continuously rather than forming a one-time checklist.</p>
<h3>3. Start with a small, owned risk register</h3>
<p>A <strong>risk register</strong> records a plausible harmful scenario, the asset affected, likelihood and impact, existing controls, a responsible owner, and the next action. State risks as scenarios: “A stolen volunteer account exposes the learner directory.” Avoid vague entries such as “hackers” that do not support a decision.</p>
<p>A simple 1–3 likelihood and impact scale helps a small team compare risks. Multiplying them can provide a teaching score, but it is not a measured probability or a financial loss estimate. Explain your assumptions. A high-consequence event can deserve attention even when a rough score is lower than another risk.</p>
<p>Choose how to treat each risk: reduce it with controls, avoid the risky activity, transfer some consequences through contracts or insurance, or accept the remaining risk with an authorised decision. Transferring consequences does not remove the need to manage security. Record <strong>residual risk</strong>: the risk that remains after treatment.</p>
<h3>4. Make controls observable</h3>
<p>For each priority action, name an owner, deadline, and evidence. “Improve backups” is weak. “Operations will restore a sample registration backup to an isolated test environment by day 30 and record the result” is reviewable. Collect enough evidence to show the control worked, without copying unnecessary learner information into an audit folder.</p>
<p>Useful measures include the proportion of privileged accounts with MFA, overdue critical updates, and the time needed to restore service in a test. Numbers need context: zero reported incidents might mean quiet operations or ineffective detection. Review trends and failures, not just attractive totals.</p>
<h3>5. Prepare for an incident before it happens</h3>
<p>A response plan names who coordinates, how to contact them, who can authorise containment, how to preserve evidence, and how communication decisions are made. Practise with a tabletop exercise: a fictional situation discussed by the people who would respond. Include a fallback contact method if normal email is unavailable.</p>
<p>For suspected account compromise, the incident lead may coordinate disabling access, revoking sessions, and preserving relevant logs. For recovery, restore trusted systems, test integrity and functionality, and watch for repeat activity. Avoid automatically wiping devices or deleting logs, which can destroy evidence. Escalate actual notification obligations through the organisation’s established process.</p>
<p>A practical first 90 days can begin with inventory and named ownership, continue with the highest-priority controls, and finish with a restore test and incident exercise. Repeat the cycle: review changes, incidents, exceptions, and whether controls still match the work. A sustainable programme is a management habit, not a document written once.</p>''',
 videos=[('Ula3TG8QS7g','Building a Cybersecurity Framework','IBM Technology','Watch for a visual introduction to the NIST framework. Use the comparison table and planning lab to cover standards, assurance, and the programme decisions.')],
 labtitle='Build the centre’s first 90-day plan',labintro='The centre has 10 staff, 20 volunteers, a cloud registration portal, and a payment provider. Volunteer passwords are reused; backups run nightly but have never been restored. Use these fictional facts to make an actionable plan.',
 steps=['Choose a risk scenario. Rate likelihood and impact from 1 (low) to 3 (high), then explain your assumptions to a study partner or in your notes.', 'Write a specific treatment with a role responsible for it, a deadline within 90 days, and evidence of completion. Use the fields below.', 'Click Review plan. Improve any missing or incomplete fields. Compare with the worked solution; the checker verifies completeness, not compliance.', 'Repeat for the other risk. Describe a response contact and a recovery test. Review both entries together: what should happen first and why? Copy your entries to your own notes before leaving the page.'],
 figures=[('programme','From a risk to an accountable action',[('Risk scenario',['Stolen volunteer account','Directory exposed']),('Treatment',['Unique logins + MFA','IT lead • within 30 days']),('Evidence + review',['Account coverage report','Review access monthly'])],'Connect each action to a risk, an owner, and evidence that it worked.')],
 workspace='''<label for="risk">Risk scenario</label><select id="risk"><option value="account">Stolen volunteer account exposes learner records</option><option value="backup">Unusable backup delays registration recovery</option></select><div class="grid"><div><label for="likelihood">Likelihood</label><select id="likelihood"><option value="1">1 · Low</option><option value="2" selected>2 · Medium</option><option value="3">3 · High</option></select></div><div><label for="impact">Impact</label><select id="impact"><option value="1">1 · Low</option><option value="2">2 · Medium</option><option value="3" selected>3 · High</option></select></div></div><label for="treatment">Treatment and why it helps</label><textarea id="treatment" maxlength="2000" placeholder="Describe the control and the risk it reduces"></textarea><label for="owner">Responsible role</label><input id="owner" maxlength="120" placeholder="For example, IT lead"><label for="deadline">Deadline in days (1–90)</label><input id="deadline" type="number" min="1" max="90" value="30"><label for="evidence">Evidence of completion</label><textarea id="evidence" maxlength="2000" placeholder="How will you show the action worked?"></textarea><button id="review-plan">Review plan</button><output id="plan-result" aria-live="polite">Your plan stays in this page. Copy it to your notes before leaving.</output>''',
 solution='''<p><strong>Account risk:</strong> likelihood 3, impact 3 is a defensible teaching estimate because passwords are reused and learner data is sensitive. Treatment: IT lead gives each volunteer a unique account, enables suitable MFA, and restricts record access within 30 days. Evidence: account inventory, MFA coverage, and the allowed/denied access tests from Module 2. Residual risk includes compromised devices and mistakes; the programme sponsor approves that risk and reviews it monthly.</p><p><strong>Backup risk:</strong> likelihood 2, impact 3 is reasonable with no restore evidence. Operations lead restores a sample backup in an isolated environment within 14 days, checks record integrity, records time to recovery, and schedules repeat tests. A failed test is useful evidence that further treatment is needed.</p><p>For a suspected export, name the incident lead, preserve logs, revoke affected sessions through the authorised process, assess scope, and coordinate communication. Recovery should restore trusted operations and verify access rules. These are example decisions, not universal scores or proof of compliance.</p><p>If the checker reports missing fields, add the owner, treatment, and evidence; use a whole-number deadline from 1 to 90. It checks presence only. Ask a reviewer whether the action is feasible and the evidence actually demonstrates success.</p>''',
 check=('A provider shows a security certificate. What should you ask next?','Ask what services and locations are in scope, whether the evidence is current, what exceptions exist, and which controls remain your responsibility.'),
 summary=['Determine scope and applicable requirements; compliance evidence and actual risk both matter.', 'Use frameworks, standards, and assurance reports according to their purpose.', 'Assign every priority risk an owner, treatment, deadline, and evidence.', 'Practise response and recovery, review residual risk, and improve continuously.'],
 sources=[('NIST · Cybersecurity Framework resources','https://www.nist.gov/cyberframework'),('ISO · ISO/IEC 27001','https://www.iso.org/standard/27001'),('PCI SSC · Official document library','https://www.pcisecuritystandards.org/document_library/'),('AICPA & CIMA · SOC suite of services','https://www.aicpa-cima.com/resources/landing/system-and-organization-controls-soc-suite-of-services')]))

modules[0]['lecture'] += '<p><strong>Second case: WannaCry (2017).</strong> This global ransomware campaign spread through vulnerable Windows systems using weaknesses in the Server Message Block (SMB) service. It demonstrates how an exposed, unpatched service can turn one compromise into widespread disruption. Contrast it with Equifax: protecting confidentiality and maintaining availability can call for overlapping controls, including verified patching and segmentation. <a href="https://www.cisa.gov/sites/default/files/Annual_Reports/NCCIC_Year_in_Review_2017_Final.pdf">The NCCIC 2017 review documents the campaign</a>.</p>'
modules[0]['videos'].append(('bPVaOlJ6ln0','Cybersecurity: Crash Course Computer Science #31','Crash Course','A beginner overview of security goals, common attacks, and defensive strategies. Use the incident log to connect these ideas to stages of an attack.'))
modules[0]['videos'].append(('_GzE99AmAQU','Hackers & Cyber Attacks: Crash Course Computer Science #32','Crash Course','Continue with attacker motivations, methods, and historical attacks. Compare the attack patterns with the Equifax and WannaCry case notes.'))
modules[2]['videos'].insert(0,('jhXCTbFnK8o','Cryptography: Crash Course Computer Science #33','Crash Course','Start with this broad introduction to encryption and key exchange. Then watch the AES explanation and use the lab to learn why tamper detection matters.'))
modules[3]['videos'].insert(0,('jhXCTbFnK8o','Cryptography: Crash Course Computer Science #33','Crash Course','Revisit the public-key and key-exchange explanation before following the TLS connection walkthrough.'))
routes=['index.html','module-2.html','module-3.html','module-4.html','module-5.html']
favicon='data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 32 32%22%3E%3Crect width=%2232%22 height=%2232%22 rx=%228%22 fill=%22%23173e39%22/%3E%3Cpath d=%22M16 5l9 4v8c0 6-9 10-9 10S7 23 7 17V9z%22 fill=%22%23d9ef88%22/%3E%3C/svg%3E'
for i,m in enumerate(modules):
    nav=''.join(f'<a href="{route}"'+(' aria-current="page"' if j==i else '')+f'><span class="num">0{j+1}</span><span>{modules[j]["title"]}</span></a>' for j,route in enumerate(routes))
    figures=''.join(picture(*f) for f in m['figures'])
    videos=''.join(f'<h3>{escape(title)}</h3><p class="small">{escape(author)}</p><iframe class="video" src="https://www.youtube-nocookie.com/embed/{vid}" title="{escape(title)} — {escape(author)}" loading="lazy" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; fullscreen" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe><p>{desc}</p><p class="small"><a href="https://www.youtube.com/watch?v={vid}">Watch on YouTube</a> if playback is blocked. Use YouTube’s captions where available; the written lesson provides a complete learning path.</p>' for vid,title,author,desc in m['videos'])
    prev=f'<a href="{routes[i-1]}">← {modules[i-1]["title"]}</a>' if i else '<span>Module 1 of 5</span>'
    nxt=f'<a href="{routes[i+1]}">{modules[i+1]["title"]} →</a>' if i<4 else '<a href="index.html">Return to Module 1 →</a>'
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{escape(m['intro'])}"><title>{m['title']} | Information Security Foundations</title><link rel="icon" type="image/svg+xml" href="{favicon}"><link rel="stylesheet" href="assets/style.css"><script src="assets/course.js" defer></script></head><body data-module="{i+1}"><a class="skip" href="#main">Skip to lesson</a><header><a class="brand" href="index.html"><span class="mark" aria-hidden="true">⌑</span><span>Information Security<br>Foundations</span></a><span class="small">An open, self-paced course<br>Learn · experiment · reflect</span></header><div class="shell"><aside><div class="course-nav"><span class="eyebrow">Your learning path</span><nav aria-label="Course modules">{nav}</nav><p class="small">Five modules. No prerequisites.<br>Begin with curiosity and a browser.</p><div class="sections"><span class="eyebrow">In this module</span><nav aria-label="Lesson sections"><a href="#objectives">Learning objectives</a><a href="#lecture">Read the lesson</a><a href="#watch">Watch &amp; learn</a><a href="#lab">Guided lab</a><a href="#summary">Takeaways</a></nav></div></div></aside><main id="main"><div class="hero"><span class="eyebrow">Module 0{i+1} / 05</span><h1>{m['title']}</h1><p class="intro">{m['intro']}</p><div class="meta"><span class="tag">{m['time']}</span><span class="tag">{m['level']}</span></div><a class="jump" href="#lecture">Begin the lesson ↓</a></div>
<section id="objectives" class="objectives"><h2>By the end, you can…</h2><ul>{''.join('<li>'+o+'</li>' for o in m['objectives'])}</ul></section>
<section id="lecture"><span class="eyebrow">01 / Read</span><h2>{m['subtitle']}</h2>{m['lecture']}</section>
<section id="watch"><span class="eyebrow">02 / Watch</span><h2>Another way into the ideas</h2><p>Choose the written lesson or combine these visual explanations with the guided exercise. The videos cover selected concepts; use the short written explanations to fill the remaining objectives.</p>{videos}</section>
<section id="lab" class="lab"><span class="eyebrow">03 / Practise</span><h2>{m['labtitle']}</h2><p>{m['labintro']}</p><p class="small">Allow 20–30 minutes. Exercises reset when you reload or leave. They do not save progress or submit your entries.</p><ol class="steps">{''.join('<li>'+s+'</li>' for s in m['steps'])}</ol>{figures}<div class="workspace">{m['workspace']}</div><noscript><p>The interactive lab needs JavaScript. You can still follow the illustrated scenario and read the worked solution below.</p></noscript>{solution(m['solution'])}</section>
<section><span class="eyebrow">04 / Reflect</span><h2>Check your understanding</h2><p>{m['check'][0]}</p><details><summary>Compare your answer</summary><p>{m['check'][1]}</p></details></section>
<section id="summary" class="summary"><h2>What to take with you</h2><ul>{''.join('<li>'+s+'</li>' for s in m['summary'])}</ul>{'<p>You have completed the learning path. Apply it to one system you use: identify an asset, a plausible threat, a control, and a way to check it.</p>' if i==4 else ''}</section>
<section class="sources"><h2>Keep exploring</h2><ul>{''.join(f'<li><a href="{url}">{title}</a></li>' for title,url in m['sources'])}</ul><p class="small">Independent educational material. External videos and resources belong to their creators; inclusion does not imply endorsement. References checked 6 October 2026.</p></section><nav class="pager" aria-label="Previous and next module">{prev}{nxt}</nav><footer>Information Security Foundations · Module {i+1} of 5<br>Practise only in these simulations or systems you own or have explicit permission to test.</footer></main></div></body></html>'''
    (DIST/routes[i]).write_text(html,encoding='utf-8')
print('Generated five course pages and six instructional illustrations.')
